import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto">
          <header>
            <Link className="text-2xl font-bold text-white" href={'/'}>Todo</Link>
            <Link className="bg-slate-100 grid place-items-center py-2 px-4 rounded-full shadow-md font-bold"  href={'/add-todo'}>Add Todo</Link>
          </header>
       <main className="p-4 text-lg">
        {children}
       </main>
        </div>
        </body>
    </html>
  );
}
